#!/bin/bash -e
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parentcmd=$(basename "${BASH_SOURCE[1]}")

usage() {
  $parentcmd help new
}

new_repo() {
  if [ -z "$1" ]; then
    usage
    exit 1
  fi

  if [ "$1" == "." ]; then
    name="$(basename $(pwd))"
    path="$(mdm dir $name 2> /dev/null)" || {
      echo "Current dir is not in $(dirname $(mdm dir))." >&2
      exit 1
    }
  else
    path="$(dirname $ROOT_DIR)/$1"
  fi

  if [ ! -d $path ]; then
    echo "About to create a new git repo at the following location:"
    echo
    echo "    $path"
    echo
    echo -n "Press enter to continue..."
    read

    mkdir -p $path
    cd $path

    yo mm-github

    if [ -d ".git" ]; then
      git add .
      git commit -am "Initial commit"
      git branch -m develop
      git checkout -b stable
      git checkout develop
    fi

    if [ -f "Podfile" ]; then
      pod install
    fi
  else
    echo "Updating existing git repo at the following location:"
    echo
    echo "    $path"
    echo
    echo -n "Press enter to continue..."
    read

    cd $path

    yo mm-github
  fi
}

new_command() {
  if [ -z "$1" ]; then
    usage
    exit 1
  fi
  path="$COMMAND_DIR/$1"
  mkdir -p $path

  if [ ! -f "$path/README.md" ];then
    cat > "$path/README.md" <<EOF
Usage: \`mdm $1\`

    TODO: Short explanation of the command.
EOF
  fi

  if [ ! -f "$path/$1" ]; then
    cd $path
    yo mm-file --name "$1" --type mdm-command
  fi

  chmod +x "$path/$1"
}

case "$1" in
  repo)     new_repo ${@:2} ;;
  command)  new_command ${@:2} ;;
  *)        usage ;;
esac
