#!/bin/bash -e
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

find_path() {
  short_reponame=${1#material-motion-}
  full_reponame="material-motion-$short_reponame"

  parent_dir="$(dirname $ROOT_DIR)"
  if [ -d "$parent_dir/$full_reponame" ]; then
    echo $parent_dir/$full_reponame
  elif [ -d "$parent_dir/$short_reponame" ]; then
    echo $parent_dir/$short_reponame
  else
    exit 1
  fi
}

case "$1" in
  "") echo $ROOT_DIR ;;
  *)  find_path "$@" ;;
esac
