#!/bin/bash -e
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cmd=$(basename "${BASH_SOURCE[0]}" | rev | cut -d'.' -f2- | rev)
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

run_installer() {
  echo "Running installer: $1"
  "$dir/installers/$1"
}

install() {
  pushd $ROOT_DIR >> /dev/null
  echo "Updating submodules..."
  git submodule init
  git submodule update
  popd >> /dev/null

  # arc
  run_installer arc

  if [ "$(uname)" == "Darwin" ]; then
    run_installer brew
  fi

  # nodejs
  run_installer nodejs

  # gh
  pushd $ROOT_DIR/third_party/gh >> /dev/null
  npm install || { \
    echo "npm install failed, requesting sudo to run npm install in $ROOT_DIR/third_party/gh..."; \
    sudo npm install; \
  }
  popd >> /dev/null

  # Yeoman tools
  run_installer yo
  run_installer generators

  # PIP-based installers
  run_installer pip
  run_installer proselint

  if [ "$(uname)" == "Darwin" ]; then
    echo "Installing mac-specific tools..."
    run_installer clang-format
    run_installer cocoapods
    run_installer sourcekitten

  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    echo "Installing linux-specific tools..."

  fi
}

list() {
  for file in $dir/installers/*; do
    echo "$( basename "$file" )"
  done
}

case "$1" in
  install)  install "${@:2}" ;;
  list)     list "${@:2}" ;;

  *) echo "Usage: $cmd [install|list]"; exit 1 ;;
esac
