#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parentcmd=$(basename "${BASH_SOURCE[1]}")
cmd=$(basename "${BASH_SOURCE[0]}")
THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set +e

usage() {
  $parentcmd help $cmd
}

open_sprint() {
  sprint_path=$(current_sprint)
  if [ $? -ne 0 ]; then
    echo "Not currently in a sprint." 2>&1
    exit 1
  fi

  sprint_url="https://github.com/$sprint_path"
  if [ "$(uname)" == "Darwin" ]; then
    open "$sprint_url"
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    xdg-open "$sprint_url"
  fi
}

current_sprint() {
  repo=$(mdm gh repo --whoami)
  token=$(mdm gh user --token)

  php "$THIS_SCRIPT_DIR/get_current_sprint.php" $repo $token

  if [ $? -ne 0 ]; then
    echo "Not currently in a sprint." 2>&1
    exit 1
  fi
}

start_sprint() {
  set +e # Disable exit on command failure.

  sprint_path=$(current_sprint)
  if [ $? -eq 0 ]; then
    echo "Already in a sprint."
    exit 1
  fi

  repo=$(mdm gh repo --whoami)
  token=$(mdm gh user --token)
  php "$THIS_SCRIPT_DIR/start_sprint.php" $repo $token

  open_sprint
}

case "$1" in
  open)         open_sprint ;;
  current)      current_sprint ;;
  start)        start_sprint ;;
  *)            usage ;;
esac
