#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Links our yeoman generators for use. Run yo --help to list the available generators.

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

readonly ROOT_DIR=$( cd "$dir/../../.." && pwd )

for file in $ROOT_DIR/generators/*; do
  name=$( basename "$file" | sed "s/generator-//" )
  cd $file
  npm install
  if [[ ! $( yo --generators | grep "^ *$name$" ) ]]; then
    echo "Linking $(basename $file) for yo..."
    npm link
  fi
done
