#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install gh - github CLI tool.

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

readonly ROOT_DIR=$( cd "$dir/../../.." && pwd )

version=$(gh --version 2> /dev/null)
if [[ $? -ne 0 || "$version" != *-mdm ]]; then
  echo "Requesting sudo to install gh..."
  cd $ROOT_DIR/third_party/gh
  sudo npm link
fi
