#!/bin/bash -e
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cmd=$(basename "${BASH_SOURCE[0]}" | rev | cut -d'.' -f2- | rev)

function editcommand {
  FILE="$BUILTIN_DIR/$1/$1"
  if [ ! -f "$FILE" ]; then
    FILE="$COMMAND_DIR/$1/$1"
    if [ ! -f "$FILE" ]; then
      echo "Unknown command $B$1$N."
      exit 1
    fi
  fi

  $EDITOR "$FILE"
}

case "$1" in
  "") echo "Usage: $cmd <command>"; exit 1 ;;

  *)  editcommand "${@:1}" ;;
esac
