#!/bin/bash
#
# Copyright 2016-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parentcmd=$(basename "${BASH_SOURCE[1]}")
cmd=$(basename "${BASH_SOURCE[0]}")

if [[ -z "$1" ]]; then
  cd "$(dirname $(git rev-parse --git-dir))"
else
  cd $($parentcmd dir "$@")
fi

# Check for Podfile-based Apple projects
podfile=$(find . -maxdepth 1 -name "Podfile")
if [ -f "$podfile" ]; then
  pod install
  workspace=$(find . -maxdepth 1 -name "*.xcworkspace")
  if [ -d "$workspace" ]; then
    open $workspace
    exit 0
  fi
fi

echo "No canonical project found in $(pwd)"
